const lines = {
  seasonArt: ['A miniature landscape with a terracotta circular gateway, greenery and mountain paths', 'Un paysage miniature avec une porte circulaire en terre cuite, de la verdure et des sentiers de montagne', 'Un paisaje en miniatura con un portal circular de terracota, vegetación y senderos de montaña'],
  home: ['Home', 'Accueil', 'Inicio'], explore: ['Explore', 'Explorer', 'Explorar'], create: ['Create', 'Créer', 'Crear'], messages: ['Messages', 'Messages', 'Mensajes'], saved: ['Saved', 'Envies', 'Guardado'],
  primary: ['Primary app navigation', 'Navigation principale', 'Navegación principal'], world: ['Your world', 'Votre univers', 'Tu mundo'], back: ['Back to World', 'Retour au Monde', 'Volver al Mundo'], skip: ['Skip to main content', 'Aller au contenu', 'Ir al contenido'], search: ['Explore opportunities', 'Explorer les possibilités', 'Explorar oportunidades'],
  season: ['A new chapter of real life.', 'Un nouveau chapitre de vie.', 'Un nuevo capítulo de vida.'], seasonLabel: ['ARO Season · concept', 'Saison ARO · concept', 'Temporada ARO · concepto'], seasonBody: ['Step outside. Meet someone. Make something together.', 'Sortir. Rencontrer. Créer quelque chose ensemble.', 'Salir. Conocer a alguien. Crear algo juntos.'], seasonAction: ['Explore the Season', 'Explorer la saison', 'Explorar la temporada'],
  messageTitle: ['Good things start with people.', 'Tout commence par une rencontre.', 'Las cosas buenas empiezan con personas.'], messageIntro: ['A calm place for your Circles and conversations.', 'Un espace serein pour vos Cercles et vos conversations.', 'Un espacio tranquilo para tus Círculos y conversaciones.'], circles: ['Circles', 'Cercles', 'Círculos'], direct: ['Direct', 'Directs', 'Directos'], sample: ['Fictional example · nothing sent or saved', 'Exemple fictif · aucun envoi ni sauvegarde', 'Ejemplo ficticio · nada enviado ni guardado'], sampleCircle: ['A Circle before the first hello.', 'Un Cercle avant le premier bonjour.', 'Un Círculo antes del primer hola.'], circleBody: ['See how a shared plan, meeting details and preparation could come together.', 'Découvrez comment réunir un programme, un lieu et les préparatifs.', 'Descubre cómo reunir el plan, el lugar y los preparativos.'], openCircle: ['Open a sample Circle', 'Ouvrir un Cercle fictif', 'Abrir un Círculo de ejemplo'], noMessages: ['Room for a first hello.', 'Une place pour un premier bonjour.', 'Espacio para un primer hola.'], noMessagesBody: ['There are no conversations in this preview. Explore an activity to see how people could connect.', 'Cet aperçu ne contient aucune conversation. Explorez une activité pour imaginer une rencontre.', 'No hay conversaciones en esta vista previa. Explora una actividad para ver cómo conectar.'],
  savedTitle: ['Make room for a someday.', 'Gardez une place pour demain.', 'Haz espacio para algún día.'], savedIntro: ['A small collection of possibilities to come back to. These examples are not your saved items.', 'Des possibilités à retrouver. Ces exemples ne sont pas vos éléments enregistrés.', 'Posibilidades para volver a explorar. Estos ejemplos no son tus elementos guardados.'], all: ['All ideas', 'Toutes les idées', 'Todas las ideas'], outdoors: ['Outdoors', 'En plein air', 'Al aire libre'], together: ['Together', 'Ensemble', 'En compañía'], searchSaved: ['Find an idea', 'Trouver une idée', 'Buscar una idea'], empty: ['No ideas match yet.', 'Aucune idée ne correspond.', 'No hay ideas que coincidan.'], clear: ['Clear filters', 'Effacer les filtres', 'Borrar filtros'], open: ['Explore this example', 'Explorer cet exemple', 'Explorar este ejemplo'], photo: ['See your city in a new light.', 'Voyez votre ville autrement.', 'Mira tu ciudad con otros ojos.'], photoBody: ['A gentle photography walk by the river.', 'Une promenade photo tranquille au bord de la rivière.', 'Un paseo fotográfico tranquilo junto al río.'], stories: ['A table. A few new stories.', 'Une table. De nouvelles histoires.', 'Una mesa. Nuevas historias.'], storiesBody: ['Conversation and a little curiosity, shared.', 'Des conversations et un peu de curiosité partagée.', 'Conversación y un poco de curiosidad compartida.'],
  chapters: ['Chapters', 'Chapitres', 'Capítulos'], worldView: ['World', 'Monde', 'Mundo'], listView: ['List', 'Liste', 'Lista'], view: ['Season view', 'Vue de la saison', 'Vista de temporada'], chapter: ['Chapter', 'Chapitre', 'Capítulo'], chosen: ['Selected chapter', 'Chapitre sélectionné', 'Capítulo seleccionado'], choose: ['Choose a chapter', 'Choisir un chapitre', 'Elegir un capítulo'], next: ['A little possibility.', 'Une petite possibilité.', 'Una pequeña posibilidad.'], concept: ['Chapter concept · no progress recorded', 'Concept de chapitre · aucune progression enregistrée', 'Concepto de capítulo · sin progreso registrado'], invitation: ['Your invitation', 'Votre invitation', 'Tu invitación'], sampleQuest: ['Explore an example activity', 'Explorer une activité fictive', 'Explorar una actividad de ejemplo'], seed: ['Try the idea studio', 'Essayer le studio d’idées', 'Probar el estudio de ideas'], keepsakes: ['Little things. Meaningful stories.', 'Petits objets. Belles histoires.', 'Pequeños objetos. Grandes historias.'], keepsakeBody: ['A glimpse of what a chapter could leave in your world. These are preview objects, not earned rewards.', 'Un aperçu de ce qu’un chapitre pourrait laisser dans votre univers. Ces objets ne sont pas des récompenses acquises.', 'Una muestra de lo que un capítulo podría dejar en tu mundo. Son objetos de muestra, no premios obtenidos.'], previewItem: ['Preview keepsake', 'Voir l’objet souvenir', 'Ver recuerdo'], pace: ['Your story, at your pace.', 'Votre histoire, à votre rythme.', 'Tu historia, a tu ritmo.'], paceBody: ['Four invitations, no race. Browse every chapter and choose what feels right for you.', 'Quatre invitations, sans course. Découvrez les chapitres et choisissez ce qui vous ressemble.', 'Cuatro invitaciones, sin carreras. Explora los capítulos y elige lo que va contigo.'], details: ['Chapter details', 'Détails du chapitre', 'Detalles del capítulo'],
};
export function experienceCopy(language = 'en') {
  const index = { en: 0, fr: 1, es: 2 }[language] ?? 0;
  return key => lines[key]?.[index] ?? key;
}
export { lines as experienceLines };
