begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public,extensions;
select plan(40);
select has_table('app_private','account_eligibility','adult declarations are private');
select has_table('app_private','account_deletion_jobs','deletion receipts and leases are private');
select ok(not has_table_privilege('authenticated','app_private.account_eligibility','INSERT'),'client cannot forge eligibility');
select ok(not has_table_privilege('anon','app_private.account_deletion_jobs','SELECT'),'anonymous caller cannot enumerate receipts');
select ok(not has_function_privilege('authenticated','api.claim_account_deletion(uuid)','EXECUTE'),'client cannot claim an account for deletion');
select ok(not has_function_privilege('anon','api.account_deletion_queue_health()','EXECUTE'),'queue health is server-only');
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,
  raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
values(null,'00000000-0000-4000-8000-000000000031','authenticated','authenticated',
  'lifecycle@aro.invalid',crypt('Synthetic-pass-031',gen_salt('bf')),now(),'{}','{"adult":true}',now(),now());
insert into auth.sessions(id,user_id,created_at,updated_at)
values('00000000-0000-4000-8000-000000000031','00000000-0000-4000-8000-000000000031',now(),now());
set local role authenticated;
set local request.jwt.claims='{"sub":"00000000-0000-4000-8000-000000000031","session_id":"00000000-0000-4000-8000-000000000031","role":"authenticated"}';
select is((api.account_access_status()->>'active')::boolean,true,'live session is recognized');
select is((api.account_access_status()->>'eligible')::boolean,false,'editable adult metadata grants no eligibility');
select is((select count(*) from public.profiles),0::bigint,'ineligible account cannot read account data');
select throws_ok($$select api.confirm_adult_eligibility((current_date-interval '17 years')::date)$$,'22023',null,'under-18 declaration is denied');
select lives_ok($$select api.confirm_adult_eligibility((current_date-interval '18 years')::date)$$,'exact 18th birthday is accepted');
select is((select count(*) from public.profiles),1::bigint,'eligible owner reads their profile');
select lives_ok($$select api.confirm_adult_eligibility('1990-01-01')$$,'repeat declaration is idempotent');
reset role;
select is((select count(*) from app_private.account_eligibility),1::bigint,'one minimal declaration exists');
update auth.sessions set not_after=now()-interval '1 second' where user_id='00000000-0000-4000-8000-000000000031';
set local role authenticated;
select is((api.account_access_status()->>'active')::boolean,false,'expired session cannot use signed JWT');
reset role;
update auth.sessions set not_after=null where user_id='00000000-0000-4000-8000-000000000031';
set local role authenticated;
set local request.jwt.claims='{"sub":"00000000-0000-4000-8000-000000000031","session_id":"invalid-session","role":"authenticated"}';
select is((api.account_access_status()->>'active')::boolean,false,'forged session is denied');
select is((select count(*) from public.profiles),0::bigint,'stale token cannot read data');
select throws_ok($$select api.request_account_deletion(repeat('a',64))$$,'42501',null,'revoked session cannot request deletion');
set local request.jwt.claims='{"sub":"00000000-0000-4000-8000-000000000031","session_id":"00000000-0000-4000-8000-000000000031","role":"authenticated"}';
select lives_ok($$select api.request_account_deletion(repeat('a',64))$$,'fresh owner can request deletion');
select lives_ok($$select api.request_account_deletion(repeat('b',64))$$,'duplicate confirmation is idempotent');
reset role;
select is((select count(*) from public.account_deletion_requests),1::bigint,'one open request remains');
update app_private.user_roles set role='admin' where user_id='00000000-0000-4000-8000-000000000031';
set local role service_role;
select is((api.claim_account_deletion(null)->>'blocked')::boolean,true,'protected admin goes to disposition review');
select is((api.account_deletion_queue_health()->>'blocked')::integer,1,'blocked queue remains visible between runs');
select ok(api.claim_account_deletion(null) is null,'review lease prevents repeated processing');
reset role;
update app_private.user_roles set role='participant' where user_id='00000000-0000-4000-8000-000000000031';
update app_private.account_deletion_jobs set lease_until=null;
set local role service_role;
select ok(api.account_deletion_receipt_status(repeat('a',64)) is null,'rotated receipt no longer authorizes status');
select is(api.account_deletion_receipt_status(repeat('b',64))->>'status','pending','current receipt reads status');
create temporary table auth3_claim as select api.claim_account_deletion(null) as payload;
select is((select payload->>'user_id' from auth3_claim),'00000000-0000-4000-8000-000000000031','worker claims exactly the requested account');
select ok(api.claim_account_deletion(null) is null,'active lease prevents concurrent worker');
select throws_ok($$select * from api.account_deletion_objects((select (payload->>'request_id')::uuid from auth3_claim),gen_random_uuid())$$,'42501',null,'forged inventory lease is denied');
select is((select count(*) from api.account_deletion_objects((select (payload->>'request_id')::uuid from auth3_claim),(select (payload->>'lease_token')::uuid from auth3_claim))),0::bigint,'empty storage is verified under the correct lease');
select throws_ok($$select api.finish_account_deletion((select (payload->>'request_id')::uuid from auth3_claim),
  (select (payload->>'lease_token')::uuid from auth3_claim))$$,'23514',null,'completion denied while Auth account exists');
reset role;
select is((select count(*) from auth.sessions where user_id='00000000-0000-4000-8000-000000000031'),0::bigint,'claim revokes every session');
select is(app_private.auth3_eligible('00000000-0000-4000-8000-000000000031'),false,'processing account disappears from public presentation');
update app_private.account_deletion_jobs set lease_until=now()-interval '1 second';
set local role service_role;
select throws_ok($$select * from api.account_deletion_objects((select (payload->>'request_id')::uuid from auth3_claim),(select (payload->>'lease_token')::uuid from auth3_claim))$$,'42501',null,'expired inventory lease fails instead of appearing empty');
reset role;
update app_private.account_deletion_jobs set lease_until=now()+interval '10 minutes';
set local role service_role;
select lives_ok($select api.mark_account_deletion_storage_clean((select (payload->>'request_id')::uuid from auth3_claim),(select (payload->>'lease_token')::uuid from auth3_claim))$,'empty inventory records durable cleanup stage');
reset role;
delete from auth.users where id='00000000-0000-4000-8000-000000000031';
set local role service_role;
select lives_ok($$select api.finish_account_deletion((select (payload->>'request_id')::uuid from auth3_claim),
  (select (payload->>'lease_token')::uuid from auth3_claim))$$,'verified Auth removal permits completion');
select is(api.account_deletion_receipt_status(repeat('b',64))->>'status','completed','receipt confirms deletion after identity is gone');
reset role;
select is((select count(*) from app_private.account_eligibility),0::bigint,'eligibility cascades with deletion');
select ok((select processed_at >= now()-interval '5 seconds' from public.account_deletion_requests),'worker completion stamps a recent processing time');
set local role service_role;
select is(api.purge_account_deletions(),0,'fresh completed receipt survives the retention window');
select * from finish();
rollback;
